ProductsCrud/Models/ErrorViewModel.cs
namespace ProductsCrud.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ProductsCrud/Models/Product.cs
using System.ComponentModel.DataAnnotations;

namespace ProductsCrud.Models
{
    public class Product
    {
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }
    }
}

ProductsCrud/Models/Supplier.cs
using System.ComponentModel.DataAnnotations;

namespace ProductsCrud.Models
{
    public class Supplier
    {
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        public ICollection<Product>? Products { get; set; }
    }
}

ProductsCrud/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using ProductsCrud.Models;

namespace ProductsCrud.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ProductsCrud/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProductsCrud.Data;
using ProductsCrud.Models;

namespace ProductsCrud.Controllers
{
    public class ProductController : Controller
    {
        private readonly AppDbContext _context;

        public ProductController(AppDbContext context)
        {
            _context = context;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var products = await _context.Products.
                                          Include(p => p.Supplier).
                                          ToListAsync();
            return View( products );
        }

        [HttpGet]
        public IActionResult Create()
        {

            ViewData["SupplierId"] = new SelectList(_context.Suppliers, "Id", "Name"); // pega os suppliers _context.Suppliers, Envia o "Id" para o bd, Mostra o "Name"

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Product newProduct)
        {
            if (ModelState.IsValid)
            {
                _context.Products.Add(newProduct);

                await _context.SaveChangesAsync();

                return RedirectToAction("Index");
            }

            ViewData["SupplierId"] = new SelectList(_context.Suppliers, "Id", "Name"); // caso de erro recarregar o dropdown

            return View(newProduct);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
                return NotFound();

            var productToEdit = await _context.Products.FirstOrDefaultAsync(p => p.Id == id);

            if (productToEdit == null)
                return NotFound();

            ViewData["SupplierId"] = new SelectList(_context.Suppliers, "Id", "Name", productToEdit.Id);
    
            return View(productToEdit);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Product productEdited)
        {
            if (ModelState.IsValid)
            {
                _context.Update(productEdited);
                await _context.SaveChangesAsync();

                return RedirectToAction("Index");
            }

            ViewData["SupplierId"] = new SelectList(_context.Suppliers, "Id", "Name", productEdited.Id);

            return View(productEdited);
        }
        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return NotFound();

            var product = _context.Products.Find(id);

            if (product == null)
                return NotFound();

            return View(product);
        }
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int? id)
        {
            var productToDelete = _context.Products.Find(id);
            
            if (productToDelete != null)
            {
                _context.Products.Remove(productToDelete);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction("Index");
        }
    }
}

ProductsCrud/Controllers/SupplierController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProductsCrud.Data;
using ProductsCrud.Models;

namespace ProductsCrud.Controllers
{
    public class SupplierController : Controller
    {
        private readonly AppDbContext _context;

        public SupplierController(AppDbContext context)
        {
            _context = context;
        }


        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var suppliers = await _context.Suppliers.ToListAsync();

            return View(suppliers);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Supplier supplier)
        {
            if (ModelState.IsValid)
            {
                 _context.Suppliers.Add(supplier);

                await _context.SaveChangesAsync();

                return RedirectToAction("Index");
            }
            return View(supplier);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
                return NotFound();

            var supplier = await _context.Suppliers.FirstOrDefaultAsync(s => s.Id == id);

            if (supplier == null)
                return NotFound();

            return View(supplier);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Supplier supplier)
        {
            if (ModelState.IsValid)
            {
                _context.Suppliers.Update(supplier);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(supplier);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return NotFound();

            var supplier = await _context.Suppliers.FindAsync(id);

            if (supplier == null)
                return NotFound();

            return View(supplier);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int? id)
        {
            var supplier = await _context.Suppliers.FindAsync(id);

            if (supplier != null)
            {
                _context.Suppliers.Remove(supplier);
                await _context.SaveChangesAsync();
            }

            return RedirectToAction("Index");
        }
    }
}

ProductsCrud/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ProductsCrud/Views/Product/Create.cshtml
@model ProductsCrud.Models.Product

@{
}


<h1>
    Register a new Product
</h1>

<div asp-validation-summary="All" class="text-danger"></div>

<form asp-action="Create" method="post">

    <label>Name:</label>
    <input asp-for="Name" />
    <label>Supplier:</label>
    <select asp-for="SupplierId" asp-items="ViewBag.SupplierId" >
        <option value="">-- Select a supplier --</option>
    </select>

    <button type="submit">Register</button>
</form>

ProductsCrud/Views/Product/Delete.cshtml
@model ProductsCrud.Models.Product
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


<h1> 
    Delete the product?
</h1>

<a asp-action="Index">Cancel</a>

<form asp-action="Delete" method="post">
    <input asp-for="Id" type="hidden" />

    <button type="submit">Delete</button>
</form>

ProductsCrud/Views/Product/Edit.cshtml
@model ProductsCrud.Models.Product
@{
}

<h1>
    Edit product
</h1>

<a asp-action="Index">Go back</a>

<form asp-action="Edit" method="post">
    <input asp-for="Id" type="hidden"/>


    <label>Name:</label>
    <input asp-for="Name" />

    <label>Supplier:</label>
    <select asp-for="SupplierId" asp-items="ViewBag.SupplierId">
        <option value="">-- Select a Supplier --</option>
    </select>

    <button type="submit">Save changes</button>
</form>

ProductsCrud/Views/Product/Index.cshtml
@model IEnumerable<ProductsCrud.Models.Product>
@{
}

<h2>
    Products list
</h2>

<a asp-action="Create">Register a new Item</a>

<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Supplier</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @item.Id
                </td>
                <td>
                    @item.Name
                </td>
                <td>
                    @item.Supplier?.Name
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>

        }
    </tbody>
</table>

ProductsCrud/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProductsCrud</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProductsCrud.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ProductsCrud</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Products</a>
                        </li>
                        <li>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Supplier" asp-action="Index">Suppliers</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - ProductsCrud - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ProductsCrud/Views/Supplier/Create.cshtml
@model ProductsCrud.Models.Supplier
@{
}

<h1>Register a new Supplier</h1>

<a asp-action="Index">Go back</a>

<form asp-action="Create" method="post">

    <label>Id:</label>
    <input asp-for="Id" />
    <label>Name:</label>
    <input asp-for="Name" />

     <button type="submit">Create</button>
</form>

ProductsCrud/Views/Supplier/Delete.cshtml
@model ProductsCrud.Models.Supplier
@{
}

<h1>Delete supplier</h1>

<a asp-action="Index">Go back</a>

<form asp-action="Delete" method="post">
    <input asp-for="Id" type="hidden"/>

    <button type="submit">Delete</button>
</form>

ProductsCrud/Views/Supplier/Edit.cshtml
@model ProductsCrud.Models.Supplier
@{
}

<h1>Edit Supplier</h1>

<a asp-action="Index">Go back</a>

<form asp-action="Edit" method="post">
    <input asp-for="Id" type="hidden"/>

    <label>Name:</label>
    <input asp-for="Name" />

    <button type="submit">Save changes</button
</form>

ProductsCrud/Views/Supplier/Index.cshtml
@model IEnumerable<ProductsCrud.Models.Supplier>
@{
}

<h1>List of Suppliers</h1>
<a asp-action="Create">Register a new supplier</a>

<table class="table">
    <thead>
        <tr>
            <th>
                Id
            </th>
            <th>
                Name
            </th>
            <th>
                Actions
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach(var supplier in Model)
        {
            <tr>
                <td>@supplier.Id</td>
                <td>@supplier.Name</td>
                <td>
                    <a asp-action="Edit" asp-route-id="@supplier.Id">Edit</a>
                    <a asp-action="Delete" asp-route-id="@supplier.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>